# Generated by Django 5.0.7 on 2024-09-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodel',
            name='food_price',
            field=models.FloatField(null=True),
        ),
    ]
