# Generated by Django 5.0.7 on 2024-09-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_foodmodel_food_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(null=True, upload_to='Media/Event_Pic')),
                ('event_name', models.CharField(max_length=100, null=True)),
                ('event_price', models.FloatField(null=True)),
                ('event_description', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
