# Generated by Django 5.0.7 on 2024-09-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_eventmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_image', models.ImageField(null=True, upload_to='Media/Chef_Pic')),
                ('chef_name', models.CharField(max_length=100, null=True)),
                ('chef_type', models.CharField(max_length=70, null=True)),
                ('chef_details', models.TextField(max_length=300)),
            ],
        ),
    ]
