# Generated by Django 5.0.7 on 2024-09-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_chefmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedTableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('booking_date', models.DateField(null=True)),
                ('booking_time', models.TimeField(null=True)),
                ('no_of_people', models.PositiveIntegerField(null=True)),
                ('message', models.TextField(max_length=300, null=True)),
            ],
        ),
    ]
