# Generated by Django 5.0.7 on 2024-09-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_rename_user_name_reservedtablemodel_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedtablemodel',
            name='booking_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reservedtablemodel',
            name='booking_time',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reservedtablemodel',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
